In [69]:
import pandas as pd
import numpy as np

In [70]:
df = pd.read_csv('train.csv')

In [71]:
df

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [72]:
df.head() #it will select the first five columns

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [73]:
df.info() # it will provide the information about the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), str(8)
memory usage: 12.1 MB

In [74]:
df.describe() # it will give some additional information about rows and columns

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

CSV

In [76]:
from io import StringIO, BytesIO

In [77]:
#creating a csv file with standard structure
data = ('col1,col2,col3\n'
       '2,3,1\n'
       '6,5,7\n'
       '9,0,8')

In [81]:
type(data)

str

In [82]:
pd.read_csv(StringIO(data)) #convert the created csv data which is in string format into a csv format

   col1  col2  col3
0     2     3     1
1     6     5     7
2     9     0     8

In [85]:
my_df=pd.read_csv(StringIO(data), usecols=['col1','col3']) #usecols is used to retieve values from particular columns

In [86]:
my_df.to_csv('Sample.csv') #converts the created csv data into a file

In [87]:
my_df1 = pd.read_csv(StringIO(data), dtype=float) # we can also define the data type of dataframe

In [88]:
my_df1

   col1  col2  col3
0   2.0   3.0   1.0
1   6.0   5.0   7.0
2   9.0   0.0   8.0

In [89]:
my_df1['col1'][2] # accessing element 2 from column1

np.float64(9.0)

In [90]:
my_df2 = pd.read_csv(StringIO(data), dtype={'col1':float, 'col2':int}) #we can also set different datatypes for columns using dtype and by defining the datatypes of particular columns

In [91]:
my_df2

   col1  col2  col3
0   2.0     3     1
1   6.0     5     7
2   9.0     0     8

In [92]:
my_df2.dtypes #it is used to check the datatypes of all the elements in dataframe

col1    float64
col2      int64
col3      int64
dtype: object

In [93]:
new_data = ('index,c1,c2,c3\n'
           '2,John,Wwe,17\n'
           '3,Batista,Wwe,14')

In [95]:
pd.read_csv(StringIO(new_data))

   index       c1   c2  c3
0      2     John  Wwe  17
1      3  Batista  Wwe  14

In [96]:
pd.read_csv(StringIO(new_data), index_col=0) #index_col is used for indexing suppose in above example index is by default shown as 0 1 and i want to take value of index column as index value then it is used

            c1   c2  c3
index
2         John  Wwe  17
3      Batista  Wwe  14

In [97]:
new_data1 = ('a,b,c\n'
           '4,apple,bat,\n'
           '3,orange,cow,')

In [98]:
pd.read_csv(StringIO(new_data1))

        a    b   c
4   apple  bat NaN
3  orange  cow NaN

In [99]:
pd.read_csv(StringIO(new_data1), index_col=False) #if index_col is set to false then it will take the elements as per the columns

   a       b    c
0  4   apple  bat
1  3  orange  cow

In [55]:
#combining usecols and index_col
new_data1 = ('a,b,c\n'
           '4,apple,bat,\n'
           '3,orange,cow,')

In [100]:
pd.read_csv(StringIO(new_data1), usecols=['b','c'], index_col=False) # using usecols and index_cols together

        b    c
0   apple  bat
1  orange  cow

In [79]:
data1 = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [101]:
pd.read_csv(StringIO(data1), escapechar='\\') # making a dataframe by using escapecharacter

                               a  b
0  hello, "Bob", nice to see you  5